Treat nil values differently from missing keys
corka149/jsonpatch pull request #17
Opened 2023-05-04 13:39 UTC by stuartc

Hey! :wave: 

I have a proposed fix for #16, I've added a default to the `get/2` function which returns `:missing` when a key is missing instead of `nil` - this appears to disambiguate nils and missing keys.

I'm _crazy_ about my use of an atom like `:missing` here, like you really never really know what a users data is going to be. Thoughts?

Fixes #16

2023-05-04 19:21 UTC, corka149 commented
You have a good solution. But indeed I am not so sure about using `:missing` as a `nil` alternative.

My suggestion would be: `:__jsonpatch_lib__missing_value__`. That should be unique enough (hopefully :D) .

2023-05-04 19:23 UTC, corka149 requested changes
Change `:missing` to `:__jsonpatch_lib__missing_value__` or something else that is long and unique enough.

2023-05-05 06:35 UTC, stuartc commented
@corka149 sounds good to me, I've changed it to `:__jsonpatch_lib__missing_value__`.

Thanks for pointing out the `[nil]` scenario, I've added a test for that as well to get those changes exercised further.

2023-05-05 19:48 UTC, corka149 approved these changes

2023-05-06 05:34 UTC, corka149 commented
Thanks again @stuartc ❤️  . I will create a release during the weekend.

2023-05-06 05:34 UTC, merged